const actions = {
  FIRST_USER_GET: "FIRST_USER_GET",
  SECOND_USER_GET: "SECOND_USER_GET",
  BATTON_IS_ACTIVE: "BATTON_IS_ACTIVE",
  CLEAR_USER: "CLEAR_USER",
  USER_ROW1: "USER_ROW1",
  USER_ROW2: "USER_ROW2",
  ADD_FIRST_STARS: "ADD_FIRST_STARS",
  ADD_SECOND_STARS: "ADD_SECOND_STARS",
  DELETE: "DELETE",
  ACTIVE_LIST: "ACTIVE_LIST",
};
export default actions;
